# Generated by Django 4.2.3 on 2023-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampleModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stTitle', models.CharField(max_length=80)),
                ('eAsset', models.PositiveSmallIntegerField(choices=[(1, 'DVD'), (3, 'Blu-ray'), (0, '-')], default=0)),
            ],
        ),
    ]
